"""initial schema

Revision ID: 1a461b5a42b4
Revises: 
Create Date: 2026-10-02 21:52:59.265493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a461b5a42b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=True),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('message', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_created_at'), ['created_at'], unique=False)

    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=True),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('message', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_created_at'), ['created_at'], unique=False)

    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heatmap_cell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('gx', sa.Integer(), nullable=False),
    sa.Column('gy', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'gx', 'gy')
    )
    with op.batch_alter_table('heatmap_cell', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_heatmap_cell_day'), ['day'], unique=False)

    op.create_table('setting',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('w', sa.Float(), nullable=False),
    sa.Column('h', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffic_sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('people_count', sa.Integer(), nullable=True),
    sa.Column('entries', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traffic_sample', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_sample_timestamp'), ['timestamp'], unique=False)

    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.String(length=32), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('entered_at', sa.DateTime(), nullable=False),
    sa.Column('exited_at', sa.DateTime(), nullable=True),
    sa.Column('dwell_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_entered_at'), ['entered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_track_id'), ['track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_zone_id'), ['zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_zone_id'))
        batch_op.drop_index(batch_op.f('ix_visit_track_id'))
        batch_op.drop_index(batch_op.f('ix_visit_entered_at'))

    op.drop_table('visit')
    with op.batch_alter_table('traffic_sample', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_sample_timestamp'))

    op.drop_table('traffic_sample')
    op.drop_table('report')
    op.drop_table('zone')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('setting')
    with op.batch_alter_table('heatmap_cell', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_heatmap_cell_day'))

    op.drop_table('heatmap_cell')
    op.drop_table('camera')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_created_at'))

    op.drop_table('alert')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_created_at'))

    op.drop_table('activity')
    # ### end Alembic commands ###
